// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Semantic_Kernel_With_Ollama_Test.Data;

#nullable disable

namespace Semantic_Kernel_With_Ollama_Test.Migrations
{
    [DbContext(typeof(AiOllamaDbContext))]
    partial class AiOllamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Semantic_Kernel_With_Ollama_Test.Domain.Produtos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescricaoBreve")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdProduto")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("IdProduto");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4a2b1d1-72f5-4e26-9e8f-0c8a9d6b3c7e"),
                            DescricaoBreve = "Laptop de alta performance para jogos.",
                            IdProduto = 1,
                            Nome = "Laptop Gamer Pro",
                            Quantidade = 15
                        },
                        new
                        {
                            Id = new Guid("a8d3e4c2-3b1f-4f9e-8a7d-1b9c0f8e5d2a"),
                            DescricaoBreve = "Mouse com design confortável para longas horas de uso.",
                            IdProduto = 2,
                            Nome = "Mouse Sem Fio Ergonômico",
                            Quantidade = 50
                        },
                        new
                        {
                            Id = new Guid("b3c9a1e8-5d2a-4f8c-9b7e-2a8d0f6c4b1e"),
                            DescricaoBreve = "Teclado com switches mecânicos e iluminação RGB.",
                            IdProduto = 3,
                            Nome = "Teclado Mecânico RGB",
                            Quantidade = 30
                        },
                        new
                        {
                            Id = new Guid("c1d8e2f7-6a3b-4e9d-8c5f-3b7a0e9d6c4a"),
                            DescricaoBreve = "Monitor curvo para uma experiência imersiva.",
                            IdProduto = 4,
                            Nome = "Monitor Ultrawide 34\"",
                            Quantidade = 20
                        },
                        new
                        {
                            Id = new Guid("d9e7f3a6-7b4c-4d8e-9a6b-4c8b1f0e7d5b"),
                            DescricaoBreve = "Fone de ouvido com som surround 7.1.",
                            IdProduto = 5,
                            Nome = "Headset Gamer 7.1",
                            Quantidade = 40
                        },
                        new
                        {
                            Id = new Guid("e6f5a4b1-8c5d-4c7f-a98c-5d9c2e1f8b6a"),
                            DescricaoBreve = "Cadeira ergonômica para longas sessões de jogos.",
                            IdProduto = 6,
                            Nome = "Cadeira Gamer Confort",
                            Quantidade = 25
                        },
                        new
                        {
                            Id = new Guid("f2a1b8c9-9d6e-4b5a-b8a7-6e0d3f2a9c7b"),
                            DescricaoBreve = "Webcam para streaming e videoconferências.",
                            IdProduto = 7,
                            Nome = "Webcam Full HD 1080p",
                            Quantidade = 60
                        },
                        new
                        {
                            Id = new Guid("a4b3c2d1-0e7f-4a6b-9c8d-7f1e4a3b2c8d"),
                            DescricaoBreve = "Armazenamento ultrarrápido para sistema e jogos.",
                            IdProduto = 8,
                            Nome = "SSD NVMe 1TB",
                            Quantidade = 35
                        },
                        new
                        {
                            Id = new Guid("b9c8d7e6-1f8a-4b9c-a7d6-8a2f5b4c3d9e"),
                            DescricaoBreve = "GPU de última geração para gráficos incríveis.",
                            IdProduto = 9,
                            Nome = "Placa de Vídeo RTX 4070",
                            Quantidade = 10
                        },
                        new
                        {
                            Id = new Guid("c7d6e5f4-2a9b-4c8d-b6e5-9b3a6c4d2e8f"),
                            DescricaoBreve = "Gabinete com bom fluxo de ar e espaço interno.",
                            IdProduto = 10,
                            Nome = "Gabinete Mid-Tower",
                            Quantidade = 22
                        },
                        new
                        {
                            Id = new Guid("d5e4f3a2-3b8c-4d7e-a5f4-0c4b7d3e1f9a"),
                            DescricaoBreve = "Fonte com certificação 80 Plus Gold.",
                            IdProduto = 11,
                            Nome = "Fonte de Alimentação 750W",
                            Quantidade = 28
                        },
                        new
                        {
                            Id = new Guid("e3f2a1b9-4c7d-4e6f-b4a3-1d5c8e2f9a8b"),
                            DescricaoBreve = "Superfície otimizada para mouses de alta precisão.",
                            IdProduto = 12,
                            Nome = "Mousepad Gamer Extra Grande",
                            Quantidade = 70
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
